set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_EMIO_tri_io[0]}]
set_property PACKAGE_PIN P19 [get_ports {GPIO_EMIO_tri_io[0]}]

set_property PACKAGE_PIN M14 [get_ports {data_p_0[15]}]
set_property PACKAGE_PIN L14 [get_ports {data_p_0[14]}]
set_property PACKAGE_PIN N15 [get_ports {data_p_0[13]}]
set_property PACKAGE_PIN M19 [get_ports {data_p_0[12]}]
set_property PACKAGE_PIN M17 [get_ports {data_p_0[11]}]
set_property PACKAGE_PIN L16 [get_ports {data_p_0[10]}]
set_property PACKAGE_PIN K17 [get_ports {data_p_0[9]}]
set_property PACKAGE_PIN L19 [get_ports {data_p_0[8]}]
set_property PACKAGE_PIN J20 [get_ports {data_p_0[7]}]
set_property PACKAGE_PIN G19 [get_ports {data_p_0[6]}]
set_property PACKAGE_PIN F19 [get_ports {data_p_0[5]}]
set_property PACKAGE_PIN G17 [get_ports {data_p_0[4]}]
set_property PACKAGE_PIN K14 [get_ports {data_p_0[3]}]
set_property PACKAGE_PIN H15 [get_ports {data_p_0[2]}]
set_property PACKAGE_PIN H16 [get_ports {data_p_0[1]}]
set_property PACKAGE_PIN J18 [get_ports {data_p_0[0]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets system_i/LTC2208_0/inst/m_axis_aclk]
set_property PACKAGE_PIN K19 [get_ports clkout_p_0]
set_property PACKAGE_PIN E18 [get_ports enc_p_0]
set_property PACKAGE_PIN K16 [get_ports of_p_0]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
