# PS EMIO LEDs, Bank 34, 3.3 V
set_property PACKAGE_PIN U15 [get_ports {GPIO_EMIO_tri_io[0]}]
set_property PACKAGE_PIN U14 [get_ports {GPIO_EMIO_tri_io[1]}]
set_property PACKAGE_PIN T15 [get_ports {GPIO_EMIO_tri_io[2]}]
set_property PACKAGE_PIN T14 [get_ports {GPIO_EMIO_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_EMIO_tri_io[*]}]

# LTC2208 LVDS data, Bank 35, 2.5 V
set_property PACKAGE_PIN B19 [get_ports {data_p_0[0]}]
set_property PACKAGE_PIN A20 [get_ports {data_n_0[0]}]
set_property PACKAGE_PIN C20 [get_ports {data_p_0[1]}]
set_property PACKAGE_PIN B20 [get_ports {data_n_0[1]}]
set_property PACKAGE_PIN E17 [get_ports {data_p_0[2]}]
set_property PACKAGE_PIN D18 [get_ports {data_n_0[2]}]
set_property PACKAGE_PIN D19 [get_ports {data_p_0[3]}]
set_property PACKAGE_PIN D20 [get_ports {data_n_0[3]}]
set_property PACKAGE_PIN E18 [get_ports {data_p_0[4]}]
set_property PACKAGE_PIN E19 [get_ports {data_n_0[4]}]
set_property PACKAGE_PIN G17 [get_ports {data_p_0[5]}]
set_property PACKAGE_PIN G18 [get_ports {data_n_0[5]}]
set_property PACKAGE_PIN H15 [get_ports {data_p_0[6]}]
set_property PACKAGE_PIN G15 [get_ports {data_n_0[6]}]
set_property PACKAGE_PIN K19 [get_ports {data_p_0[7]}]
set_property PACKAGE_PIN J19 [get_ports {data_n_0[7]}]
set_property PACKAGE_PIN J20 [get_ports {data_p_0[8]}]
set_property PACKAGE_PIN H20 [get_ports {data_n_0[8]}]
set_property PACKAGE_PIN K14 [get_ports {data_p_0[9]}]
set_property PACKAGE_PIN J14 [get_ports {data_n_0[9]}]
set_property PACKAGE_PIN J18 [get_ports {data_p_0[10]}]
set_property PACKAGE_PIN H18 [get_ports {data_n_0[10]}]
set_property PACKAGE_PIN M19 [get_ports {data_p_0[11]}]
set_property PACKAGE_PIN M20 [get_ports {data_n_0[11]}]
set_property PACKAGE_PIN L16 [get_ports {data_p_0[12]}]
set_property PACKAGE_PIN L17 [get_ports {data_n_0[12]}]
set_property PACKAGE_PIN M17 [get_ports {data_p_0[13]}]
set_property PACKAGE_PIN M18 [get_ports {data_n_0[13]}]
set_property PACKAGE_PIN L14 [get_ports {data_p_0[14]}]
set_property PACKAGE_PIN L15 [get_ports {data_n_0[14]}]
set_property PACKAGE_PIN N15 [get_ports {data_p_0[15]}]
set_property PACKAGE_PIN N16 [get_ports {data_n_0[15]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_p_0[*] data_n_0[*]}]

# LTC2208 LVDS data clock and overflow
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets system_i/LTC2208_0/inst/m_axis_aclk]
set_property PACKAGE_PIN H16 [get_ports clkout_p_0]
set_property PACKAGE_PIN H17 [get_ports clkout_n_0]
set_property PACKAGE_PIN F16 [get_ports of_p_0]
set_property PACKAGE_PIN F17 [get_ports of_n_0]
set_property IOSTANDARD LVDS_25 [get_ports {clkout_p_0 clkout_n_0 of_p_0 of_n_0}]

# LTC2208 single-ended controls, Bank 35, 2.5 V
set_property PACKAGE_PIN J16 [get_ports {GPIO_LTC2208_CTRL_tri_o[0]}]
set_property PACKAGE_PIN M15 [get_ports {GPIO_LTC2208_CTRL_tri_o[1]}]
set_property PACKAGE_PIN M14 [get_ports {GPIO_LTC2208_CTRL_tri_o[2]}]
set_property PACKAGE_PIN K16 [get_ports {GPIO_LTC2208_CTRL_tri_o[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_LTC2208_CTRL_tri_o[*]}]

# AD8370 IF VGA, Bank 34, 3.3 V
set_property PACKAGE_PIN U19 [get_ports {AD8370_GPIO_0_tri_o[0]}]
set_property PACKAGE_PIN U20 [get_ports {AD8370_GPIO_0_tri_o[1]}]
set_property PACKAGE_PIN T20 [get_ports {AD8370_GPIO_0_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD8370_GPIO_0_tri_o[*]}]

# LMX2572 GPIO: channel 1 outputs are CE, CSB, SCK, SDI for devices 0/1/2.
set_property PACKAGE_PIN U17 [get_ports {GPIO_LMX2572_tri_o[0]}]
set_property PACKAGE_PIN P14 [get_ports {GPIO_LMX2572_tri_o[1]}]
set_property PACKAGE_PIN T16 [get_ports {GPIO_LMX2572_tri_o[2]}]
set_property PACKAGE_PIN P15 [get_ports {GPIO_LMX2572_tri_o[3]}]
set_property PACKAGE_PIN T10 [get_ports {GPIO_LMX2572_tri_o[4]}]
set_property PACKAGE_PIN T11 [get_ports {GPIO_LMX2572_tri_o[5]}]
set_property PACKAGE_PIN Y14 [get_ports {GPIO_LMX2572_tri_o[6]}]
set_property PACKAGE_PIN U13 [get_ports {GPIO_LMX2572_tri_o[7]}]
set_property PACKAGE_PIN V15 [get_ports {GPIO_LMX2572_tri_o[8]}]
set_property PACKAGE_PIN V17 [get_ports {GPIO_LMX2572_tri_o[9]}]
set_property PACKAGE_PIN W15 [get_ports {GPIO_LMX2572_tri_o[10]}]
set_property PACKAGE_PIN W16 [get_ports {GPIO_LMX2572_tri_o[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_LMX2572_tri_o[*]}]

# LMX2572 GPIO: channel 2 inputs are MUXOUT lock detect for devices 0/1/2.
set_property PACKAGE_PIN R14 [get_ports {GPIO_LMX2572_MUX_tri_i[0]}]
set_property PACKAGE_PIN T12 [get_ports {GPIO_LMX2572_MUX_tri_i[1]}]
set_property PACKAGE_PIN V16 [get_ports {GPIO_LMX2572_MUX_tri_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_LMX2572_MUX_tri_i[*]}]

# RF frontend switches and PE43711B-Z attenuator, Bank 34, 3.3 V
set_property PACKAGE_PIN W20 [get_ports {GPIO_RF_FRONTEND_tri_o[0]}]
set_property PACKAGE_PIN Y19 [get_ports {GPIO_RF_FRONTEND_tri_o[1]}]
set_property PACKAGE_PIN Y18 [get_ports {GPIO_RF_FRONTEND_tri_o[2]}]
set_property PACKAGE_PIN V18 [get_ports {GPIO_RF_FRONTEND_tri_o[3]}]
set_property PACKAGE_PIN V20 [get_ports {GPIO_RF_FRONTEND_tri_o[4]}]
set_property PACKAGE_PIN Y17 [get_ports {GPIO_RF_FRONTEND_tri_o[5]}]
set_property PACKAGE_PIN Y16 [get_ports {GPIO_RF_FRONTEND_tri_o[6]}]
set_property PACKAGE_PIN W14 [get_ports {GPIO_RF_FRONTEND_tri_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_RF_FRONTEND_tri_o[*]}]

#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets clk]
