#ifndef TEST_XPARAMETERS_H
#define TEST_XPARAMETERS_H

#define XPAR_AXI_GPIO_0_DEVICE_ID 0U
#define XPAR_AXI_GPIO_1_DEVICE_ID 1U
#define XPAR_AXI_GPIO_2_DEVICE_ID 2U
#define XPAR_AXIDMA_0_DEVICE_ID 0U
#define XPAR_FABRIC_AXI_DMA_0_S2MM_INTROUT_INTR 0U
#define XPAR_PS7_DDR_0_S_AXI_BASEADDR 0U
#define XPAR_SCUGIC_SINGLE_DEVICE_ID 0U
#define XPAR_XUARTPS_0_BASEADDR 0U

#endif
